#!/usr/bin/env bash

# === TODO ===
# - Add packages!


set -e  # Exit on (t)error


# === Globals ===
INDENT=0

NAME=null
SOURCE_DIR=null
LIBRARY_DIR=null
BUILD_DIR=null
BINARY_DIR=null
MAIN=null
FLAGS=()


# === CLI helpers ===
cli-indent() {
    local _indent=$((INDENT - ${#1}))

    if [ "$INDENT" -gt 0 ]; then
       printf "%*s" "$_indent" ""
    else
       printf ""
    fi
}

cli-format() {
    printf "\033[%sm[%s]\033[0m" "$1" "$2"
}

cli-header() {
    echo -e "$(cli-format 31 "$1")"
}

cli-good() {
    echo -e "$(cli-format 32 "$1")"
}

cli-bad() {
    echo -e "$(cli-format 31 "$1") $(cli-indent "$1")$2"
}

cli-command() {
    echo -e "$(cli-format 36 "$1") $(cli-indent "$1")$2"
}

cli-info() {
    local _title="info"

    echo -e "$(cli-format 34 "$_title") $(cli-indent "$_title")$1"
}

cli-pure() {
    echo -e "   $(cli-indent "")$1"
}

cli-prompt() {
    echo -e -n "$(cli-format 35 "$1?") $(cli-indent "$1?")"
}


# === Utility ===
config() {
    local -a _flags

    while read -r line || [[ $line ]]; do
          IFS=':' read -ra parts <<< "$line"

          key=$(echo "${parts[0]}" | xargs)
          value=$(echo "${parts[1]}" | xargs)

          case "$key" in
               "name")        NAME="$value"        ;;
               "source-dir")  SOURCE_DIR="$value"  ;;
               "library-dir") LIBRARY_DIR="$value" ;;
               "build-dir")   BUILD_DIR="$value"   ;;
               "binary-dir")  BINARY_DIR="$value"     ;;
               "main")        MAIN="$value"        ;;
               "flags")       _flags="$value"      ;;
          esac
    done < "$1.matic"

    if [ -z "$NAME" ] || [ -z "$SOURCE_DIR" ] || [ -z "$BUILD_DIR" ] || [ -z "$BINARY_DIR" ] || [ -z "$MAIN" ]; then
       cli-bad "oh no!" "the project's .matic file is missing one or more values"
       exit 1
    fi

    if [ -n "$_flags" ]; then
       IFS=' ' read -ra FLAGS <<< "$_flags"
    fi

    FLAGS+=("-i$SOURCE_DIR")

    if [ -n "$LIBRARY_DIR" ]; then
       FLAGS+=("-i$LIBRARY_DIR")
    fi
}

make-dir() {
    if [ -d "$1" ]; then
       cli-info "found directory \"$1\""
    else
       cli-info "creating directory \"$1\""
       mkdir -p "$1"
    fi
}


# === Flags ===
flag-gaslight() {
    local _hie

    INDENT=11

    cli-command "gaslighting" "gaslighting, gatekeeping & girlbossing hls"
    cli-pure                  "(you might want to restart your editor)"

    _hie="cradle:\n  direct:\n    arguments:"

    for i in "${!FLAGS[@]}"; do
        _hie+="\n      - ${FLAGS[$i]}"
    done

    _hie+="\n      - -fno-code"

    echo -e "$_hie" > "hie.yaml"

    cli-good "done"
}

flags() {
    case "$1" in
         -gaslight) flag-gaslight ;;
         *)                       ;;
    esac
}

# === Create ===
create() {
    local _file

    INDENT=18

    cli-command "creating" "starting a new .matic file"

    _file=""

    cli-prompt  "project name"
    read -r _name
    if [ "$_name" = "" ]; then
       cli-bad "oh no!" "your project needs a name"
       exit 1
    fi
    _file+="name:        $_name"

    cli-prompt "source directory"
    read -r _source_dir
    if [ "$_source_dir" = "" ]; then
       _source_dir="src"
    fi
    make-dir "$_source_dir"
    _file+="\nsource-dir:  $_source_dir"

    cli-prompt "library directory"
    read -r _library_dir
    if [ "$_library_dir" != "" ]; then
        make-dir "$_library_dir"
       _file+="\nlibrary-dir: $_library_dir"
    fi

    cli-prompt "build directory"
    read -r _build_dir
    if [ "$_build_dir" = "" ]; then
       _build_dir="build"
    fi
    make-dir "$_build_dir"
    _file+="\nbuild-dir:   $_build_dir"

    cli-prompt "binary directory"
    read -r _binary_dir
    if [ "$_binary_dir" = "" ]; then
       _binary_dir="bin"
    fi
    make-dir "$_binary_dir"
    _file+="\nbinary-dir:  $_binary_dir"

    cli-prompt "main file"
    read -r _main
    if [ "$_main" = "" ]; then
       _main="main.hs"
    fi
    if [ -f "$_source_dir/$_main" ]; then
       cli-info "found file \"$_main\""
    else
       cli-info "creating file \"$_main\""
       echo -e "module Main where\n\n\nmain :: IO ()\nmain = putStrLn \"hi!\"" > "$_source_dir/$_main"
    fi
    _file+="\nmain:        $_main"

    cli-prompt "flags"
    read -r _flags
    if [ "$_flags" != "" ]; then
       _file+="\nflags:       $_flags"
    fi

    cli-info "creating .matic file \"$_name.matic\""
    echo -e "$_file" > "$_name.matic"

    cli-good "done"
}

# === Build ===
build() {
    INDENT=8

    cli-command "building" "$NAME"
    make-dir    "$BUILD_DIR"
    make-dir    "$BINARY_DIR"
    cli-info    "building \"$BINARY_DIR/$NAME\""
    ghc --make "${FLAGS[@]}" -outputdir "$BUILD_DIR" -o "$BINARY_DIR/$NAME" "$SOURCE_DIR/$MAIN"
    cli-good    "done"
}

# === Run ===
run() {
    INDENT=7

    cli-command "running" "$BINARY_DIR/$NAME"
    ./"$BINARY_DIR/$NAME"
    cli-good    "done"
}

# === Watch ===
watch() {
    local _state
    local _next

    INDENT=8

    if [ -n "$LIBRARY_DIR" ]; then
       cli-command "watching" "directories \"$SOURCE_DIR\", \"$LIBRARY_DIR\""
       _state=$(find "$SOURCE_DIR" "$LIBRARY_DIR" -type f -print0 | xargs -0 shasum | awk '{print $1}' | sort -n)
    else
       cli-command "watching" "directory \"$SOURCE_DIR\""
       _state=$(find "$SOURCE_DIR" -type f -print0 | xargs -0 shasum | awk '{print $1}' | sort -n)
    fi

    cli-pure    "(press ⌃c to stop)"

    build
    run

    while true; do

          if [ -n "$LIBRARY_DIR" ]; then
             _next=$(find "$SOURCE_DIR" "$LIBRARY_DIR" -type f -print0 | xargs -0 shasum | awk '{print $1}' | sort -n)
          else
             _next=$(find "$SOURCE_DIR" -type f -print0 | xargs -0 shasum | awk '{print $1}' | sort -n)
          fi

          if [[ "$_state" != "$_next" ]]; then
             cli-info "something changed"
             build
             run
             _state="$_next"
          fi

          sleep 4
    done
}

# === Clean ===
clean() {
    INDENT=8

    cli-command "cleaning" ""

    find "$BUILD_DIR" -name "*.hi" -o -name "*.o" | while read -r file; do
         rm -f "$file"
    done
    rm -rf "$BUILD_DIR"

    find "$BINARY_DIR" -name "*" | while read -r file; do
         rm -f "$file"
    done
    rm -rf "$BINARY_DIR"

    cli-good    "done"
}

# === Usage ===
usage() {
    INDENT=8
    cli-command "usage"    "$0 {command} {flags}"
    cli-command "commands" "create       → initializes a new project"
    cli-pure               "build {name} → builds the project"
    cli-pure               "run {name}   → builds & runs the project"
    cli-pure               "watch {name} → watches the project source, rebuilds & runs it on updates"
    cli-pure               "clean {name} → nukes everything for a clean slate"
    cli-command "flags"    "-gaslight    → bullies hls into shutting up forever"
}

# === CLI ===
cli-header "haskell build-o-matic™ 5000"
case "$1" in
     create) create
             ;;
     build)  config "$2"
             flags "$3"
             build
             ;;
     run)    config "$2"
             flags "$3"
             build
             run
             ;;
     watch)  config "$2"
             flags "$3"
             watch
             ;;
     clean)  config "$2"
             clean
             ;;
     *)      usage
             ;;
esac
